In [15]:
import pandas as pd
from sklearn import linear_model

In [16]:
df = pd.read_csv('insurance_data.csv')
df

    age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(df[['age']],df[['bought_insurance']],test_size=0.2)

In [19]:
X_train

    age
8    62
26   23
18   19
7    60
13   29
6    55
17   58
15   55
3    52
20   21
24   50
0    22
2    47
9    61
5    56
19   18
25   54
4    46
16   25
23   45
1    25

In [20]:
X_test

    age
21   26
22   40
11   28
12   27
14   49
10   18

In [21]:
y_train

    bought_insurance
8                  1
26                 0
18                 0
7                  1
13                 0
6                  0
17                 1
15                 1
3                  0
20                 0
24                 1
0                  0
2                  1
9                  1
5                  1
19                 0
25                 1
4                  1
16                 1
23                 1
1                  0

In [22]:
y_test

    bought_insurance
21                 0
22                 1
11                 0
12                 0
14                 1
10                 0

In [23]:
model = linear_model.LogisticRegression()
model.fit(X_train,y_train)
model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 1, 0, 0, 1, 0])